version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache_poc
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4_poc
        depends_on:
          - php

    mysql:
        image: mysql
        container_name: sf4_mysql_poc
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        #volumes: .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4

    php:
        build: .docker/php
        container_name: sf4_php_poc
        volumes:
          - .:/home/wwwroot/sf4_poc
        #environment: maildev_host=sf4_maildev
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmy_admin_poc
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8085:80
        links:
            - mysql